name: site_grupo_rmts
description: Site institucional Grupo RMTS em Flutter Web
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  webviewx_plus: ^0.5.1
  font_awesome_flutter: ^10.4.0
  # se quiser responsividade extra, dÃ¡ para adicionar mais libs depois

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/logos/clientes/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
